name=flysky-receiver
version=1.0.0
author=Liam Ramirez-Guess
sentence=Simply FlySky iBUS receiver wrapper using IBusBM
paragraph=This Lib provides easy channel and switch reading capabilities. 
category=Communication
architectures=*
depends=IBusBM